language: node_js
node_js:
    - "8.9.1"
before_script:
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - "npm run build"
os:
    - linux
    - windows
